spring:
  config:
    activate:
      on-profile: paypal



paypal:
#  client-id: CLIENT_ID
  client-id: AS7KHtmX39btRIQdebEkXhXdHbFHJHFM3GW_3u0R3cZHOuDwb0TiCPpwsUBrpNvxAHFKnrRdYQvuOUrb
#  client-secret: CLIENT_SECRET
  client-secret: EI3sQbg5KIDkzDye8YmFi9yNrIppFRuAJ122Lt9vqyIUB4iAHr-mGv0EithI-NZqbCRv2Qhr57Oh-tkg
  mode: sandbox # dev mode  (use 'sandbox' for testing and 'live' for production)
